version: '3.4'

services:
    
  primecaremed.frontend:
    image: ${DOCKER_REGISTRY-}primecaremedfrontend
    build:
      context: .
      dockerfile: src/PrimeCareMed.Frontend/Dockerfile
    environment:
      CONNECTION_STRING: "Host=postgres;Port=5432;Database=postgres;Username=admin;Password=root;Integrated Security=true;Pooling=true;"


  primecaremed.api:
    image: ${DOCKER_REGISTRY-}primecaremedapi
    build:
      context: .
      dockerfile: src/PrimeCareMed.API/Dockerfile
    environment:
       CONNECTION_STRING: "Host=postgres;Port=5432;Database=postgres;Username=admin;Password=root;Integrated Security=true;Pooling=true;"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
